date: "April, 2023"
hedylink: "https://hedy.org/hedy/l/efb4XvX"
python_windows: "https://apps.microsoft.com/store/detail/python-311/9NRWMJP3717K"
python_osx: "https://www.python.org/ftp/python/3.11.3/python-3.11.3-macos11.pkg"
jitsi_link: "https://jitsi.thecolliers.xyz/April2023"
moderators: "https://jitsi.thecolliers.xyz/April2023"
youtube_link_A: "https://www.youtube.com/watch?v=CTvFFGlOxL4"
youtube_link_B: "https://www.youtube.com/watch?v=TnCbFpxKmcY"
youtube_link_C: "https://www.youtube.com/watch?v=CTvFFGlOxL4"
